name: CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Set up Node.js
      # uses: actions/setup-node@v2
      #  with:
      #    node-version: 14

      # - name: Set up Azure CLI
      # uses: azure/login@v1
      
      - name: Log in to Azure
        run: az login --service-principal --username ${{ secrets.APP_ID }} --password ${{ secrets.APP_SECRTE }} --tenant ${{ secrets.TENANT_ID }}
      
      - name: Terraform initialise
        id: init
        run: terraform init

      - name: Terraform version
        run: terraform version


      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
